### ISSUE TITLE
API fix

### ISSUE THREAD

**Issue by adamdab** [PW-MiNI-IO2-2023-Group-3/Specyfikacja#14]
* move parameters in get form query to body
* add maxplace for event creation
* Confirmation token as GET not as POST in account confirmation

**Comment by Xevi8X** [comment]
Ad 1. Ok
Ad 2. maxplace in POST /events is named "freeplace" - Organizer sets number of all available place for event. You can rename it to maxplace.
Ad 3. Ok - imo, its POST bcs main purpose of POST /organizer/{id} is to send activation code. It may return just 200 without organizer object. To get info about organizer use GET /organizer

Nevertheless, sound great, I'm looking forward to see implementation.

**Comment by Xevi8X** [comment]
Ad.3 bis: If the only reason to change POST->GET is to make tricky confirmation by link, I have to disappoint you. The initial idea was to add screen with place to write/copy code from email. Technically inserting code is POST apperation bcs it put data into db.

If you really want to have activatation link instead of code (what has many disadvantages, there are many reason, what for example Microsoft send code in email) you can always make you own undokumented endpoint with GET that will bypass request to POST /organizer{id}.
